tools: bugfix in bulk mode
parameter name has been changed from csv to input to support individual.

$ python stdk-keygen.py --input sn.csv
Traceback (most recent call last):
  File "stdk-keygen.py", line 281, in <module>
    main()
  File "stdk-keygen.py", line 278, in main
    bulk(args)
  File "stdk-keygen.py", line 212, in bulk
    print(args.csv)
AttributeError: 'Namespace' object has no attribute 'csv'

Signed-off-by: Sanghee Kim <sh0130.kim@samsung.com>