deps/json: Fix multiple definition of main error
Json Makefile was including cJSON/test.c for build.
Since this file contains a main() function call, building
stdk project was leading to the following error:
multiple definition of `main`
cJSON_test.o:test.c:(.text+0x644): first defined here

Also cJSON_Utils.c file was unused and has been removed from build