make: remove generated root ca certificate
To make clean a build environment.

If existed this file in local, it makes problem when
we want to change a branch as follow.

error: The following untracked working tree files would be overwritten by checkout:
	src/certs/root_ca.pem
Please move or remove them before you switch branches.

Signed-off-by: Sanghee Kim <sh0130.kim@samsung.com>
(cherry picked from commit 9f1f9e9f69afa58bf7d7b4f53fa7f31571b55dfb)