net: openssl: fix build error on esp32
BSP of ESP32 doesn't have SSL_library_init so occurs build error.
Add SSL_library_init function in iot-core instead of chipset bsp
for other chipsets as weak function.

apps/esp32/smart_switch/build/src/libsrc.a(iot_net_openssl.o):(.literal._iot_net_ssl_connect+0x8): undefined reference to `SSL_library_init'
apps/esp32/smart_switch/build/src/libsrc.a(iot_net_openssl.o): In function `_iot_net_ssl_connect':
iot-core/src/port/net/openssl/iot_net_openssl.c:30: undefined reference to `SSL_library_init'
collect2: error: ld returned 1 exit status

Signed-off-by: Yongsul Oh <46733179+YongsulOh@users.noreply.github.com>